# Required
OPENAI_API_KEY='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'
ANTHROPIC_API_KEY='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'
OPENAI_LLM='gpt-4o'